### ISSUE TITLE
Update to 6.11 ?

### ISSUE THREAD

**Issue by karlkashofer** [inindev/visionfive2#1]
Hi!
According to https://rvspace.org/en/project/JH7110_Upstream_Plan the PCIe patches have been accepted in the upstream kernel.
Would you have time to update your repo to 6.11 ? That would be great ! 
Thanks for the easy way to build a minimal debian image with everything but the kernel from the repos !
Cheers,
KK

**Comment by inindev** [comment]
Thanks for pointing this out.  I will update the repo once 6.11 is released.

**Comment by karlkashofer** [comment]
Hey ! Great ! Thanks !
