### ISSUE TITLE
/sys/class/pwm/ empty

### ISSUE THREAD

**Issue by karlkashofer** [inindev/visionfive2#2]
Hey ! Thanks for updating to 6.11, it runs great !

I have a fan attached to the board and control its speed by writing into /sys/class/pwm/pwmchip0
However, that does not exist when i boot your 6.11 kernel.
Do you know what to do ?

**Comment by inindev** [comment]
It must be missing or renamed from the device tree: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/riscv/boot/dts/starfive/jh7110-common.dtsi?h=v6.11

Is it renamed or something similar?  I will be able to search for it in the class directories this evening.

**Comment by karlkashofer** [comment]
Thanks ! This dtbs business is beyond me...

**Comment by karlkashofer** [comment]
Maybe because PWM has not been merged yet ?
[https://rvspace.org/en/project/JH7110_Upstream_Plan](url)

**Comment by inindev** [comment]
Thanks for the heads-up, I missed that. I will patch it into the kernel & rebuild.

**Comment by inindev** [comment]
wget https://github.com/inindev/visionfive2/releases/download/v13-6.11.0-2/linux-image-6.11.0-2-riscv64_6.11.0-2_riscv64.deb
sudo dpkg -i linux-image-6.11.0-2-riscv64_6.11.0-2_riscv64.deb

**Comment by inindev** [comment]
did this resolve your issue?

**Comment by karlkashofer** [comment]
Yes, it did ! Thanks !
