### ISSUE TITLE
CONFIG_TUN=y

### ISSUE THREAD

**Issue by maleadt** [inindev/visionfive2#3]
Thanks for packaging Debian for VF2! I just installed the 6.11 image (almost flawlessly; the uBoot default env didn't boot the NVME by default), and I had one request: Could you enable `CONFIG_TUN` in the kernel? That would enable use of Tailscale.

If not, I can just build my own kernel, but I figured I'd ask first 🙂

**Comment by inindev** [comment]
I see that kernel 6.11.3 is in review now: https://lore.kernel.org/stable/ZwUzyi7A%2FUG4pr3P@duo.ucw.cz/T/#t

When this is released I can rebuild with the ```CONFIG_TUN``` flag.

I am surprised to learn that it did not just boot NVMe without additional actions.  I will test this again too.

**Comment by maleadt** [comment]
> I see that kernel 6.11.3 is in review now: https://lore.kernel.org/stable/ZwUzyi7A%2FUG4pr3P@duo.ucw.cz/T/#t
> 
> When this is released I can rebuild with the `CONFIG_TUN` flag.

Thanks!


> I am surprised to learn that it did not just boot NVMe without additional actions. I will test this again too.

Although I erased all `mtd` partitions and flashed your SPL and uBoot images from the 6.11 release, the default boot action was simply `run mmc_boot`. Changing that to `run nvme_boot` didn't work either, it seems like an `nvme scan` is needed first? I went with a `setenv devnum 0; nvme scan; run nvme_boot; if test $? != 0; then run mmc_boot; fi` custom boot command, which seems to work fine.

**Comment by maleadt** [comment]
> > I see that kernel 6.11.3 is in review now: https://lore.kernel.org/stable/ZwUzyi7A%2FUG4pr3P@duo.ucw.cz/T/#t
> > When this is released I can rebuild with the `CONFIG_TUN` flag.
> 
> Thanks!

In the mean time, I discovered you already had a placeholder in the build script to tweak the configuration, which works just fine:

```patch
 config_fixups() {
     local lpath="$1"
+
+    # Enable CONFIG_TUN
+    sed -i 's/# CONFIG_TUN is not set/CONFIG_TUN=y/' "$lpath/.config"
+    make -C "$lpath" ARCH=riscv olddefconfig
 }
```

**Comment by inindev** [comment]
https://github.com/inindev/visionfive2/releases/tag/v13-6.11.3

```sudo dpkg -i linux-image-6.11.3-1-riscv64_6.11.3-1_riscv64.deb```

I will package a new debian image soon that wraps-up this latest config so you don't have to install it separately.

**Comment by maleadt** [comment]
Works great, thanks!
